version: '1.0'

services:
  phishing-management:
    build:
      context: ./phishing-management
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=mongodb://mongodb:27017/mongo?authSource=admin
      - PORT=3001
      - EMAIL_SERVICE_URL=http://phishing-simulation:3002/phishing/send
    depends_on:
      - mongodb
    networks:
      - app-network

  phishing-simulation:
    build:
      context: ./phishing-simulation
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - DATABASE_URL=mongodb://mongodb:27017/mongo?authSource=admin
      - PORT=3002
      - JWT_SECRET=your_jwt_secret
      - PHISHING_URL=http://localhost:3002/phishing/landing-page
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=mussish99@gmail.com
      - SMTP_PASS=your_app_password
      - PHISHING_SENDER_EMAIL=hello@demomailtrap.com
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=http://phishing-management:3001
    depends_on:
      - phishing-management
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
